services:
  - type: web
    name: auca-cert-system
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cert-db
          property: connectionString

databases:
  - name: cert-db
    plan: free
